### ISSUE TITLE
Fatal error in console commands

### ISSUE THREAD

**Issue by zhukovra** [urmaul/yii-slack-log#1]
I'm trying send error messages with simple `throw new \Exception()` in console command and get fatal error:
```
PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/crm/protected/vendor/urmaul/yii-slack-log/src/Target.php:127
Stack trace:
#0 /var/www/crm/protected/vendor/urmaul/yii-slack-log/src/Target.php(76): urmaul\yii\log\slack\Target->formatMessages()
#1 /var/www/crm/protected/vendor/yiisoft/yii/framework/logging/CLogRoute.php(104): urmaul\yii\log\slack\Target->processLogs(Array)
#2 /var/www/crm/protected/vendor/yiisoft/yii/framework/logging/CLogRouter.php(108): CLogRoute->collectLogs(Object(CLogger), true)
#3 /var/www/crm/protected/vendor/yiisoft/yii/framework/base/CComponent.php(561): CLogRouter->collectLogs(Object(CEvent))
#4 /var/www/crm/protected/vendor/yiisoft/yii/framework/logging/CLogger.php(352): CComponent->raiseEvent('onflush', Object(CEvent))
#5 /var/www/crm/protected/vendor/yiisoft/yii/framework/logging/CLogger.php(340): CLogger->onFlush(Object(CEvent))
#6 /var/www/crm/protected/vendor/yiisoft/yii/framework/logging/CLogRouter.php(120): CLogger->flush(true)
#7 /var/www/crm/protected/vendor/yiisoft/yii in /var/www/crm/protected/vendor/urmaul/yii-slack-log/src/Target.php on line 127
```

It falls because `attachmentLink` after that code is `null`, but after you concatenate `$attachments` and `attachmentLink`
```
try {
    $currentUrl = Yii::app()->request->hostInfo . Yii::app()->request->requestUri;
    $text .= '>Current URL: <' . $currentUrl . '>' . "\n";
    
    $attachmentLink = ['title_link' => $currentUrl];
} catch (\Exception $exc) {}

...

$attachments[] = [
    'fallback' => $message[0],
    'title' => $title,
    'text' => $message[0],
    'color' => 'danger',
    'mrkdwn_in' => ['text'],
] + $attachmentLink;
```

**Comment by urmaul** [comment]
Thanks for detailed description. Fixed.
I have no yii1 application nearby to test it so let me know if fix doesn't work.

**Comment by zhukovra** [comment]
@urmaul wow! I'm impressed with your speed. Thank you!
